#' Geometric mean of ligand and receptor
#' @description This function caculates the geometric mean of ligand and receptor. Average expression of ligand comes from source celltype, and verage expression of receptor comes from target celltype
#' @param CCC_conserved_sumary dataframe, result of the ligand receptor analysis(for example, ConservedCCI[[2]]). It must contain column: Source, Target
#' @param specie_conserved_CCC dataframe, also result of the ligand receptor analysis(for example, ConservedCCI$Conserved_ligand_receptor$sp1_orthg_ccc_df). It must contain 4 column for ligand, receptor, source celltype, target celltype
#' @param seurat_object a seurat object contains the expression data for celltypes of source and target
#' @param avg_group a character, which variable used to average the expression, usally "celltype"
#' @param species_set species_set should only contain two characters, like "Mm" to label the species
#'
#' @return
#' @export
#'
#' @examples
#' LRpair_show <- get_average_expression(CCC_conserved_sumary = ConservedCCI[[2]], specie_conserved_CCC = ConservedCCI$Conserved_ligand_receptor$sp1_orthg_ccc_df, seurat_object = Mm_seurat_object, avg_group = "celltype", species_set = "Mm")
get_average_expression <- function(CCC_conserved_sumary, specie_conserved_CCC, seurat_object, avg_group = "celltype", species_set = "Zf") {
  LRpair_show_all_zf <- data.frame("LR" = paste(specie_conserved_CCC[[1]], specie_conserved_CCC[[2]], sep = "_"), "Cell_Pair" = paste(specie_conserved_CCC[[3]], specie_conserved_CCC[[4]], sep = "_"))
  index <- as.vector(unlist(sapply(paste(CCC_conserved_sumary$Source, CCC_conserved_sumary$Target, sep = "_"), function(x) grep(x, LRpair_show_all_zf$Cell_Pair))))
  LRpair_show <- LRpair_show_all_zf[index,]
  LRpair_show$Source <- as.vector(unlist(sapply(LRpair_show$Cell_Pair, function(x) strsplit(x, split = "_")[[1]][1])))
  LRpair_show$Target <- as.vector(unlist(sapply(LRpair_show$Cell_Pair, function(x) strsplit(x, split = "_")[[1]][2])))
  LRpair_show$Ligand <- as.vector(unlist(sapply(LRpair_show$LR, function(x) strsplit(x, split = "_")[[1]][1])))
  LRpair_show$Receptor <- as.vector(unlist(sapply(LRpair_show$LR, function(x) strsplit(x, split = "_")[[1]][2])))
  unique_LR <- unique(c(LRpair_show$Ligand, LRpair_show$Receptor))
  unique_LR_avg <- as.data.frame(Seurat::AverageExpression(seurat_object, features = unique_LR, group.by = avg_group))
  colnames(unique_LR_avg) <- gsub("RNA\\.", "", colnames(unique_LR_avg))
  colnames(unique_LR_avg) <- gsub("\\.", " ", colnames(unique_LR_avg))
  for (i in 1:nrow(LRpair_show)) {
    l_avg <- unique_LR_avg[match(LRpair_show$Ligand[i], rownames(unique_LR_avg)), match(LRpair_show$Source[i], colnames(unique_LR_avg))]
    r_avg <- unique_LR_avg[match(LRpair_show$Receptor[i], rownames(unique_LR_avg)), match(LRpair_show$Target[i], colnames(unique_LR_avg))]
    LRpair_show$ligand_source_avg[i] <- l_avg
    LRpair_show$receptor_target_avg[i] <- r_avg
    LRpair_show$ligand_receptor_avg[i] <- sqrt(l_avg * r_avg)
  }
  LRpair_show$species <- species_set
  return(LRpair_show)
}

#' Merge the average expression dataframe
#' @description This function merge the average expression dataframe of two species generated by function get_average_expression
#' @param LRpair_show_df1 LRpair_show_df1 must contain columns: Cell_Pair, species, ligand_receptor_avg. Besides, check and make column species only contain two characters
#' @param LRpair_show_df2 LRpair_show_df2 must contain columns: Cell_Pair, species, ligand_receptor_avg, Besides, check and make column species only contain two characters
#'
#' @return
#' @export
#'
#' @examples
#' merge_width_df <- Merge_data_for_heatmap(LRpair_show_Mm, LRpair_show_Zf)
Merge_data_for_heatmap <- function(LRpair_show_df1, LRpair_show_df2) {
  library(tidyverse)
  merge_LRpair_show <- data.frame()
  for (i in 1:max(nrow(LRpair_show_df1), nrow(LRpair_show_df2))) {
    if (i <= nrow(LRpair_show_df1)) {
      merge_LRpair_show <- rbind(merge_LRpair_show, LRpair_show_df1[i, ])
    }
    if (i <= nrow(LRpair_show_df2)) {
      merge_LRpair_show <- rbind(merge_LRpair_show, LRpair_show_df2[i, ])
    }
  }
  merge_LRpair_show <- merge_LRpair_show %>% mutate(Cell_Pair2 = paste0(species, Cell_Pair))
  merge_LRpair_show <- merge_LRpair_show %>% mutate(LR2 = LR)
  for (i in seq(2, nrow(merge_LRpair_show), 2)) {
    if (merge_LRpair_show$LR2[i] != merge_LRpair_show$LR2[i-1]) {
      merge_LRpair_show$LR2[i] <- merge_LRpair_show$LR2[i-1]
    }
  }
  merge_LRpair_show_width_df_2 <- merge_LRpair_show[,c("LR2", "Cell_Pair2", "ligand_receptor_avg")] %>%
    tidyr::pivot_wider(
      names_from = "LR2",
      values_from = "ligand_receptor_avg"
    )
  make_rowname_lr2 <- as.vector(unlist(merge_LRpair_show_width_df_2[1]))
  merge_LRpair_show_width_df_2 <- merge_LRpair_show_width_df_2[, -1]
  rownames(merge_LRpair_show_width_df_2) <- make_rowname_lr2
  return(merge_LRpair_show_width_df_2)
}

#' Plot heatmap for average exprssion of ligand and receptor pair
#' @description Plot a heatmap for average exprssion of ligand and receptor pair in two species
#' @param width_df dataframe, the result of function Merge_data_for_heatmap.
#' @param filename character, file name saved for this pheatmap
#' @param color_pheatmap_set, default is NULL, it can be grDevices::colorRampPalette(c('blue','white','red'))(100), or viridis::viridis(8)
#' @param colors_list default is NULL, it can be colors_list <- list(species = c(Mm = rgb(102/255,46/255,115/255), Zf = rgb(31/255,153/255,139/255)))
#' @param annotation_names_col logical, whether annotation the column
#' @param border_color character. color of the border
#' @param scale default is none, scale by row or by column
#' @param cluster_rows logical, whether cluster the rows
#' @param cluster_cols logical, whether cluster the columns
#' @param legend logical, whether draw the legend
#' @param legend_breaks default is NA
#' @param legend_labels default is NA
#' @param show_rownames logical, whether show rownames
#' @param show_colnames logical, whether show colnames
#' @param fontsize integer, size of the font
#' @param cellwidth integer, size of the cell width
#' @param cellheight integer, size of the cell height
#' @param width integer, the width of the pheatmap
#' @param height integer, the height of the pheatmap
#'
#' @return a pheatmap in your directory
#' @export
#'
#' @examples
#' colors_list <- list(species = c(Mm = rgb(102/255,46/255,115/255), Zf = rgb(31/255,153/255,139/255)))
#' pheatmap_LR(width_df = merge_width_df, filename = "lr_avg_pheatmap.pdf", colors_list = colors_list)
pheatmap_LR <- function(width_df,
                        filename = "Pheatmap_LR.pdf",
                        color_pheatmap_set = NULL,
                        colors_list = NULL,
                        annotation_names_col = TRUE,
                        border_color = "white",
                        scale = "none",
                        cluster_rows = FALSE,
                        cluster_cols = FALSE,
                        legend = TRUE,
                        legend_breaks = NA,
                        legend_labels = NA,
                        show_rownames = T,
                        show_colnames = T,
                        fontsize = 8,
                        cellwidth = 10,
                        cellheight = 8,
                        width = 14,
                        height = 14) {
  anno_row_df <- data.frame("source_target" = rownames(width_df), "species" = substr(rownames(width_df), start = 1, stop = 2))
  rownames(anno_row_df) <- anno_row_df$source_target
  anno_row_df <- anno_row_df[-1]
  LRpair_show_rename_row <- substr(rownames(width_df), start = 3, stop = nchar(rownames(width_df)))
  if (is.null(color_pheatmap_set)) {
    color_pheatmap = viridis::viridis(8)
  } else {
    color_pheatmap = color_pheatmap_set
  }
  if (is.null(colors_list)) {
    colors_list = list(species = c(rgb(102/255,46/255,115/255), rgb(31/255,153/255,139/255)))
  } else {
    color_pheatmap = colors_list
  }
  pheatmap::pheatmap(width_df,
                     color = color_pheatmap,
                     annotation_row =  anno_row_df,
                     annotation_colors = colors_list,
                     annotation_names_col = annotation_names_col,
                     labels_row = LRpair_show_rename_row,
                     border_color = border_color,
                     scale = scale,
                     cluster_rows = cluster_rows,
                     cluster_cols = cluster_cols,
                     legend = legend,
                     legend_breaks = legend_breaks,
                     legend_labels = legend_labels,
                     show_rownames = show_rownames,
                     show_colnames = show_colnames,
                     fontsize = fontsize,
                     cellwidth = cellwidth,
                     cellheight = cellheight,
                     filename = filename,
                     width = width,
                     height = height)
}
