#' Identify markers of each cluster
#' @description This function first identify marker genes in each cluster
#' with Roc threshold > RocThr. Then, based on the marker genes identified above,
#' this function calculates the difference and power of marker genes in each
#' cluster, and marker genes with Difference threshold > DiffThr will be retained.
#' Next, gene with the largest power in which cluster will be the marker
#' gene in this cluster. Finally, marker genes with
#'
#' @param Seurat_object Seurat object, should contain cluster information
#' @param RocThr numeric, indicating the cutoff of Roc to identify marker genes
#' @param DiffThr numeric, indicating the cutoff of difference in marker genes between
#' clusters
#' @param Spec1 character, When GeneSymb1 == NULL, inner file will be used for
#' ID changing, this parameter indicate the species of
#' @param GeneSymb1 Gene correspondence that is used for ID chaning. first
#' column should be ENSEMBLE ID, second column should be Symbol, third column
#' should be NCBIID and fourth column should be officalsymbol.
#' @param FracThr1 numeric, indicating the threshold of estimate of the odds
#' ratio
#'
#' @return
#' @export
#'
#' @examples
Identify_Markers<-function(Seurat_object, RocThr=0.4, DiffThr=1/3, Spec1=NULL, GeneSymb1=NULL, FracThr=3 ){
  if (is.null(GeneSymb1)) {
    if (Spec1=='Mm') {
      GeneSymb1 = MmscRNA_genes
    }else if (Spec1=='Hs') {
      GeneSymb1 = HsscRNA_genes
    }else if (Spec1=='Zf') {
      GeneSymb1 = ZfscRNA_genes
    }else if (Spec1=='Ch') {
      GeneSymb1 = ChscRNA_genes
    }else if (is.null(Spec1)){
      print('please input correct ')
    }
  }
  MarkerRoc<-Identify_Markers1(Seurat_object,RocThr)
  MarkerRoc<-as.data.frame(MarkerRoc)
  Marker<-Identify_Markers2(Seurat_object,MarkerRoc,GeneSymb1=GeneSymb1,
                            PowerThr1=DiffThr)
  final_Markers<-Refine_Markers(Seurat_object,Spec1,GeneSymb1,Marker,FracThr)
  return(final_Markers)
}


#' Format marker genes for plotting
#' @description Order the gene expression in each cluster to make the heatmap
#' look better
#' @param Marker_genes data.frame, generated by \code{\link{Identify_Markers}}
#' @export
#'
#' @examples
Format_Markers_Frac<-function(Marker_genes){
  RNA1 <- Marker_genes
  Cluster1 <- t(apply(RNA1, 1, function(x1){
    x21 <- strsplit(x1[1],',')[[1]]; x22 <- strsplit(x1[2],',')[[1]]
    x31 <- paste(x21[1:(length(x21)-1)], collapse=',')
    x32 <- paste(x22[1:(length(x22)-1)], collapse=',')
    return(c(x21[1], x31, x32))
  }))
  colnames(Cluster1) <- c('Cluster','AllCluster','Power')
  RNA2 <- cbind(Cluster1, RNA1[,3:ncol(RNA1)])
  if(grepl('TRUE', paste(grepl('^[Rr]p[ls]\\d', RNA2[, 'Symbol']), collapse=''))){
    RNA3 <- RNA2[-grep('^[Rr]p[ls]\\d', RNA2[, 'Symbol']), ]
  }else{ RNA3 <- RNA2 }
  RNA3 <- RNA3[order(RNA3[, 'Power'], decreasing=T), ]
  RNA3 <- RNA3[order(RNA3[, 'AllCluster']), ]
  RNA3 <- RNA3[order(RNA3[, 'Cluster']), ]; print(c(nrow(RNA2), nrow(RNA3)))
  return(RNA3)
}


Identify_Markers1<-function(Seurat_object, PowerThr1=1/3){
  Marker0 <- FindAllMarkers(object = Seurat_object, test.use ='roc', return.thresh = PowerThr1)
  Marker1 <- as.data.frame(Marker0)
  Marker2 <- Marker1[Marker1[,'avg_diff']>0 & Marker1[,'power']>PowerThr1,]
  uMarker2 <- unique(Marker2[,'gene'])
  MarkerRoc1 <- Cal_MarkersRoc(Seurat_object, uMarker2)
  MarkerRoc2 <- Select_MarkersPower(MarkerRoc1)
  return(MarkerRoc2)
}




Select_MarkersPower <- function(MarkerRoc01){

  MarkerRoc02 <- t(Revise_MarkersPower(MarkerRoc01))
  colnames(MarkerRoc02) <- gsub('_power','',colnames(MarkerRoc02))
  Power02 <- c()
  for(i in 1:dim(MarkerRoc02)[1]){
    MarkerRoc03 <- t(as.matrix(MarkerRoc02[i,seq(3,dim(MarkerRoc02)[2],3)]))
    Power01 <- Sort_MarkersPower(MarkerRoc03,0)
    Power02 <- rbind(Power02,Power01)
  }
  rownames(Power02) <- rownames(MarkerRoc02)
  colnames(Power02) <- c('Cluster','Power','Diff')

  return(Power02)
}



Revise_MarkersPower <- function(MarkerRoc01){
  MarkerRoc02 <- apply(MarkerRoc01,1,function(x01){
    for(i0 in seq(2,length(x01),3)){
      if(x01[i0]<0){ x01[i0+1] <- -x01[i0+1] }
    }
    return(x01)
  } )

  return(MarkerRoc02)
}



Sort_MarkersPower <- function(MarkerRoc01,Thr01=0){

  MarkerRoc02 <- sort.int(as.numeric(MarkerRoc01),index.return=T,decreasing=T)
  Name01 <- colnames(MarkerRoc01)
  if(length(MarkerRoc01)==0|max(MarkerRoc02$x)<=Thr01){
    MarkerRoc03 <- c('', '', '');
  }else if(length(MarkerRoc02$x)==1 & length(MarkerRoc02$x[MarkerRoc02$x>Thr01])==1 |
           length(MarkerRoc02$x)!=1 & length(MarkerRoc02$x[MarkerRoc02$x>Thr01])==1 & MarkerRoc02$x[2]<0){
    MarkerRoc03 <- c(paste(Name01[MarkerRoc02$ix[1]],paste0('Ctr',Thr01),sep=','), paste(MarkerRoc02$x[1],Thr01,sep=','), MarkerRoc02$x[1]);
  }else{
    if(length(MarkerRoc02$x)!=1 & length(MarkerRoc02$x[MarkerRoc02$x>Thr01])==1){
      MarkerRoc02x <- MarkerRoc02$x[1:2]
      MarkerRoc02ix <- MarkerRoc02$ix[1:2]
    }else{
      MarkerRoc02x <- c(MarkerRoc02$x[MarkerRoc02$x>Thr01],Thr01)
      MarkerRoc02ix <- c(MarkerRoc02$ix[MarkerRoc02$x>Thr01],length(MarkerRoc02$ix)+1)
      Name01 <- c(Name01,paste0('Ctr',Thr01))
    }
    Power01 <- Cal_RelativePower(MarkerRoc02x)
    maxPower01 <- which.max(Power01)
    if(maxPower01==length(MarkerRoc02x)){ maxPower01=length(Power01)-1; }

    MarkerRoc03 <- c(paste(Name01[MarkerRoc02ix[1:(maxPower01+1)]],collapse=','), paste(MarkerRoc02x[1:(maxPower01+1)],collapse=','), max(Power01));
  }

  return(MarkerRoc03)
}


Identify_Markers2 <- function(pbmc, Marker, GeneSymb1=NULL, PowerThr1=1/3){

  TotoalCluster <- length(unique(pbmc@active.ident))
  MarkerRoc1 <- Marker
  NumCluster <- apply(MarkerRoc1,1,function(X1){length(strsplit(as.character(X1[1]),',')[[1]])})
  MarkerRoc2 <- cbind(MarkerRoc1,NumCluster)
  MarkerRoc3 <- MarkerRoc2[MarkerRoc2$Diff>PowerThr1 & MarkerRoc2$NumCluster>1 & MarkerRoc2$NumCluster<=(ceiling(TotoalCluster/4)+1),]

  Cluster1 <- strsplit(levels(as.factor(MarkerRoc3$Cluster)),',')
  Cluster3 <- c()
  for(i in 1:length(Cluster1)){
    Cluster2 <- Cluster1[[i]]
    Cluster3 <- c(Cluster3,Cluster2[1:(length(Cluster2)-1)])
  }
  uCluster3 <- unique(Cluster3)

  Num1 <- c(); MarkerRoc5 <- c()
  for(i in 1:length(uCluster3)){ print(uCluster3[i])
    Cluster4 <- gsub('C','',uCluster3[i])
    MarkerRoc4 <- MarkerRoc3[grep(paste0(uCluster3[i],','),MarkerRoc3$Cluster),]
    Num1 <- rbind(Num1,c(uCluster3[i],dim(MarkerRoc4)[1]))
    if(dim(MarkerRoc4)[1]>0){
      MarkerRoc5 <- rbind(MarkerRoc5,cbind(MarkerRoc4,Cluster4,rownames(MarkerRoc4)))
    }
  }
  colnames(MarkerRoc5)[c(1,dim(MarkerRoc5)[2]-1,dim(MarkerRoc5)[2])] <- c('AllCluster','cluster','gene')
  colnames(Num1) <- c('Cluster','NumMarkers')
  Num1 <- Num1[order(Num1[,'Cluster']),]
  print(Num1)

  MarkerRoc51 <- apply(MarkerRoc5,1,function(x1){ x11 <- strsplit(as.character(x1[1]),',')[[1]]; x12 <- paste(x11[1:(length(x11)-1)],collapse=',')
  x21 <- strsplit(as.character(x1[2]),',')[[1]]; x22 <- paste(x21[1:(length(x21)-1)],collapse=',')
  return(c(x12,x22))
  })
  MarkerRoc52 <- cbind(t(MarkerRoc51),MarkerRoc5[,5:6])
  colnames(MarkerRoc52)[1:2] <- colnames(MarkerRoc5)[1:2]

  MarkerRoc53 <- cbind(MarkerRoc52, GeneSymb1[match(MarkerRoc52$gene,GeneSymb1[,1]),4])
  colnames(MarkerRoc53)[ncol(MarkerRoc53)] <- 'Symbol'

  return(MarkerRoc53)
}


Markertest <- function(object, cells.1, cells.2, genes.use = NULL, print.bar = TRUE,
                       assay.type = "RNA") {
  data.test <- Seurat::GetAssayData(
    object = object,
    slot = "data"
  )
  if (is.null(genes.use)) {
    genes.use <- rownames(x = data.test)
  }
  to.return <- AUCMarkerTest(
    data1 = data.test[, cells.1],
    data2 = data.test[, cells.2], mygenes = genes.use, print.bar = print.bar
  )
  to.return$power <- abs(x = to.return$myAUC - 0.5) * 2
  return(to.return)
}



Refine_Markers<-function(Seurat_obejct, Spec1, GeneSymb1, Marker, FracThr1=3){
  if(Spec1=='Zf'){ Cluster1 <- 'res.0.2' }else{ Cluster1 <- 'res.0.1' }
  MarkerRoc3 <- Identify_Markers3(Seurat_obejct, Marker, Cluster1, GeneSymb1, FracThr1=FracThr1)
  Ind1 <- grep('Symbol', colnames(MarkerRoc3))
  if(length(Ind1)>1){ MarkerRoc3 <- MarkerRoc3[, -Ind1[2]] }
  MarkerRoc4 <- MarkerRoc3[MarkerRoc3[,'Pvalue'] < 0.01, -grep('EnsemblID', colnames(MarkerRoc3))]
  print(c(nrow(MarkerRoc3), nrow(MarkerRoc4)))
  return(MarkerRoc4)
}



Identify_Markers3 <- function(pbmc, MarkerRoc2, Cluster1, Symb1, FracThr1=5){

  pbmc@assays$RNA@data <- GetAssayData(pbmc)[rownames(MarkerRoc2), ]
  Frac1 <- Get_scRNA_AggExp(pbmc, Symb1, Cluster1=Cluster1, ExpType1='fraction')
  colnames(Frac1) <- gsub('_0', '', colnames(Frac1))
  colnames(Frac1) <- gsub('Frac', '', colnames(Frac1))
  MarkerRoc3 <- cbind(MarkerRoc2, Frac1)
  AllCluster1 <- as.matrix(table(pbmc@active.ident))
  rownames(AllCluster1) <- paste0('C', rownames(AllCluster1))

  MarkerRoc31 <- apply(MarkerRoc3, 1, function(x1){
    x11 <- strsplit(x1[1], ',')[[1]]
    x12 <- x11[1:(length(x11)-1)]; x13 <- setdiff(rownames(AllCluster1), x12)
    TNum11 <- as.numeric(AllCluster1[match(x12, rownames(AllCluster1)),1])
    TNum12 <- as.numeric(AllCluster1[match(x13, rownames(AllCluster1)),1])
    Frac11 <- as.numeric(x1[match(x12, names(x1))]); mFrac11 <- which.min(Frac11)
    Frac12 <- as.numeric(x1[match(x13, names(x1))]); mFrac12 <- which.max(Frac12)
    TNum21 <- TNum11[mFrac11]; TNum22 <- TNum12[mFrac12]
    Frac21 <- Frac11[mFrac11]; Frac22 <- Frac12[mFrac12]
    TNum31 <- round(TNum21*Frac21); TNum32 <- round(TNum22*Frac22)

    Num4 <- matrix(c(TNum31, TNum21-TNum31, TNum32, TNum22-TNum32), nrow=2)
    Test1 <- fisher.test(Num4)
    if(Frac22!=0){
      if(as.numeric(Test1$estimate)/Frac22 < FracThr1){ return(Frac22)
      }else{ return(Test1$p.value) }
    }else{ return(Test1$p.value) }

  })
  MarkerRoc4 <- cbind(MarkerRoc3, MarkerRoc31)
  colnames(MarkerRoc4)[ncol(MarkerRoc4)] <- 'Pvalue'

  return(MarkerRoc4)
}




Get_scRNA_AggExp <- function(pbmc, Symb1, Cluster1=c('all', 'res.0.1'), Group1=c('all', 'protocol'), ExpType1=c('expression', 'fraction')){

  source('../Markers_Programs/Programs/Converse_GeneIDSymbol.R')

  if(Cluster1[1]=='all'){ pbmc@meta.data[,'all'] <- 0
  }else if(!is.element(Cluster1, colnames(pbmc@meta.data))){
    stop(paste('please input one of', paste(colnames(pbmc@meta.data)[grep('res',colnames(pbmc@meta.data))], collapse=',') ))
  }
  if(Group1[1]=='all'){ pbmc@meta.data[,'all'] <- 0
  }else if(!is.element(Group1, colnames(pbmc@meta.data))){
    stop(paste('please input one of', paste(colnames(pbmc@meta.data), collapse=',') ))
  }

  Meta01 <- pbmc@meta.data
  Cluster2 <- sort(unique(Meta01[, Cluster1[1]]))
  Group2 <- sort(unique(Meta01[, Group1[1]]))

  Name01 <- c(); flag01 <- 0;
  for(i0 in 1:length(Cluster2)){
    for(j0 in 1:length(Group2)){
      Cell01 <- Meta01[Meta01[, Cluster1[1]]==Cluster2[i0] & Meta01[, Group1[1]]==Group2[j0], ]
      Object02 <- as.matrix(GetAssayData(pbmc)[, rownames(Cell01)]); print(c(Cluster2[i0], as.character(Group2[j0]), ncol(Object02)))

      if(ncol(Object02)==0){
      }else{
        Frac1 <- t(apply(Object02, 1, function(x1){
          x12 <- length(x1[x1!=0])
          x2 <- x12/length(x1)
          return(c(x12, x2))
        }))
        if(is.element('expression', ExpType1) & is.element('fraction', ExpType1)){ mObject03 <- cbind(rowMeans(Object02), Frac1[,2])
        Name01 <- c(Name01, paste0(c('Exp','Frac'),paste0('C',Cluster2[i0],'_',Group2[j0])))
        }else if(is.element('expression', ExpType1)){ mObject03 <- rowMeans(Object02)
        Name01 <- c(Name01, paste0('ExpC',Cluster2[i0],'_',Group2[j0]))
        }else if(is.element('fraction', ExpType1)){ mObject03 <- Frac1[,2]
        Name01 <- c(Name01, paste0('FracC',Cluster2[i0],'_',Group2[j0]))
        }else if(is.element('number', ExpType1)){ mObject03 <- Frac1[,1]
        Name01 <- c(Name01, paste0('NumC',Cluster2[i0],'_',Group2[j0]))
        }else{ stop(paste0('Please choose ExpType1 for expression or fraction')) }

        if(flag01==0){ mObject04 <- mObject03; flag01 <- 1;
        }else{ mObject04 <- cbind(mObject04, mObject03) }
      } } }
  mObject04 <- as.matrix(mObject04); colnames(mObject04) <- Name01
  if(is.element('expression', ExpType1) & is.element('fraction', ExpType1)){
    mObject04 <- mObject04[, c(seq(1,ncol(mObject04),2), seq(2,ncol(mObject04),2))]
  }

  if(grepl('^ENS', rownames(GetAssayData(pbmc))[1])){
    GeneID1 <- Converse_GeneIDSymbol(rownames(mObject04), Symb1)
    mObject05 <- cbind(GeneID1, mObject04)
  }else{ mObject05 <- mObject04 }

  return(mObject05)
}
