#' plot the heatmap of marker genes across different species
#' @param RNA1 correlation of expression in each cell type
#' @param RowType1 character, indicating the cell types that you want to show
#' on the row in heatmap. RowType1='' means show all cell types
#' @param ColType1 character, indicating the cell types that you want to show
#' on the column in heatmap. RowType1='' means show all cell types
#' @param cluster_cols boolean values determining if columns should be clustered
#' or hclust object
#' @param cluster_rows boolean values determining if rows should be clustered or
#'
#' hclust object
#' @param Color1 vector of colors used in heatmap
#' @export
#' @importFrom pheatmap pheatmap
#' @importFrom grDevices rgb
#' @importFrom grDevices colorRampPalette
#' @importFrom methods is
#' @return pheatmap object
#'
#' @examples
Heatmap_Cor <- function(RNA1, RowType1='', ColType1='', cluster_cols=T
                        , cluster_rows=F, Color1=NULL){
  validInput(RowType1,'RowType1','character')
  validInput(ColType1,'ColType1','character')
  validInput(cluster_cols,'cluster_cols','logical')
  validInput(cluster_rows,'cluster_rows','logical')
  Ind21 <- c(); Ind22 <- c();
  if(RowType1==''){ Ind21 <- 1:dim(RNA1)[1];
  }else{
    for(i in 1:length(RowType1)){
      Ind1 <- grep(RowType1[i], rownames(RNA1))
      Ind21 <- c(Ind21, Ind1)
    }
  }

  if(ColType1==''){ Ind22 <- 1:dim(RNA1)[2]
  }else{
    for(i in 1:length(ColType1)){
      Ind1 <- grep(ColType1[i], colnames(RNA1))
      Ind22 <- c(Ind22, Ind1)
    }
  }
  RNA2 <- RNA1[Ind21, Ind22]
  #RNA2[RNA2==1] <- NA; RNA2[is.na(RNA2)] <- max(RNA2[!is.na(RNA2)])

  white1 <- rgb(230/255,230/255,230/255); purple1 <- rgb(192/255,103/255,169/255)
  purple2 <- rgb(148/255,43/255,112/255);
  blue1 <- rgb(72/255,85/255,167/255); red1 <- rgb(239/255,58/255,37/255)
  black1 <- rgb(71/255,71/255,71/255); yellow1 <- rgb(250/255,240/255,21/255);
  if(is.null(Color1)){ Color1 <- c(blue1, 'white', red1) }

  Hier1 <- pheatmap::pheatmap(as.matrix(RNA2), cluster_cols =cluster_cols, cluster_rows =
                      cluster_rows, color = colorRampPalette(Color1)(50),
                    border_color=rgb(200/255,200/255,200/255))

  return(Hier1)
}

#' Title
#'
#' @param RNA1 correlation of expression in each cell type
#' @param CellType cell type. First column should be Species, second column should
#' be Cluster, third column should be CellType, fourth column should be Group
#'
#' @return
#' @export
#'
#' @examples
Rename_CellType<-function(RNA1,CellType){
  CellT2 <- cbind(apply(CellType, 1, function(x1){ x2 <- paste0(x1[1],x1[2]) })
                  , CellType)
  colnames(RNA1) <- apply(CellT2[match(colnames(RNA1), CellT2[, 1]), ],
                          1, function(x1){ x2 <- paste(c(x1[2],'.',x1[4])
                                                       ,collapse='') })
  rownames(RNA1) <- apply(CellT2[match(rownames(RNA1), CellT2[, 1]), ],
                          1, function(x1){ x2 <- paste(c(x1[2],'.',x1[4])
                                                       ,collapse='') })
  RNA1[RNA1==1] <-NA
  return(RNA1)
}





Seurat_SubsetData <- function(pbmc1, SubG1, SubS1=NULL, ExSubS1=NULL){

  if(!is.null(SubS1)){ CellN1 <- c()
  for(SubS2 in SubS1){
    CellN1 <- c(CellN1, rownames(pbmc1@meta.data[pbmc1@meta.data[, SubG1]==SubS2, ]))
  }
  pbmc1 <- subset(pbmc1, cells=unique(CellN1) )
  }

  if(!is.null(ExSubS1)){ CellN2 <- c()
  for(ExSubS2 in ExSubS1){
    CellN2 <- c(CellN2, rownames(pbmc1@meta.data[pbmc1@meta.data[, SubG1]==ExSubS1, ]))
  }
  CellN1 <- setdiff(rownames(pbmc1@meta.data), CellN2)
  pbmc1 <- subset(pbmc1, cells=unique(CellN1) )
  }

  return(pbmc1)
}



#' Plot the Marker genes in each cluster
#'
#' @param scRNA1 dataframe, generated by
#' @param ModuleScale1 change the relative proportion of module bar and expression heatmap
#' @param Color1 vector of colors used in heatmap
#' @param ModuleColor1 colors for each moudle
#' @param Gene1 genes that you want to show in the pheatmap
#' @param NumRowBlank the blank between each group
#' @param show_colnames logic, indicating whether show column names
#' @param legend1 logic, indicating whether show the legend
#' @param Scale character indicating if the values should be centered and scaled
#' in either the row direction or the column direction, or none. Corresponding
#' values are "row", "column" and "none"
#' @importFrom pheatmap pheatmap
#' @importFrom gridExtra grid.arrange
#' @importFrom grDevices rgb
#' @importFrom grDevices colorRampPalette
#' @importFrom stats kmeans
#' @importFrom stats hclust
#' @importFrom stats as.dist
#' @importFrom stats cor
#' @return
#' @export
#'
#' @examples
Plot_MarkersHeatmap<-function(scRNA1, ModuleScale1=15,
                              Color1=NULL, ModuleColor1=NULL, Gene1=NULL,
                              NumRowBlank=0,show_colnames=F, legend1=T,
                              Scale='none'){
  Scale1 <- Scale
  RevOrder1 <- -1
  scRNA12 <- scRNA1[, c(grep('Cluster\\d', colnames(scRNA1)))]
  RowGroup1 <- as.numeric(apply(scRNA1, 1, function(x1){ x2 <- gsub('Cluster','', x1[4]) }))
  FigWH1 <- c(ncol(scRNA12)/5, 10); NumRowBlank1=NumRowBlank
  white1 <- rgb(230/255,230/255,230/255); purple1 <- rgb(192/255,103/255,169/255)
  purple2 <- rgb(148/255,43/255,112/255);
  if (is.null(Color1)) {
    Color1 <- c(white1, purple1, purple2)
  }
  if (is.null(ModuleColor1)) {
    Col2 <- c(rgb(247/255,147/255,30/255), rgb(248/255,115/255,106/255),
              rgb(220/255,20/255,60/255), rgb(169/255,169/255,169/255),
              rgb(150/255,206/255,180/255), rgb(163/255,165/255,0/255),
              rgb(192/255,193/255,48/255), rgb(157/255,115/255,194/255),
              rgb(183/255,76/255,171/255), rgb(230/255,134/255,201/255),
              rgb(140/255,198/255,63/255), rgb(255/255,191/255,15/255),
              rgb(103/255,199/255,193/255), rgb(3/255,161/255,198/255),
              rgb(97/255,156/255,255/255), rgb(129/255,70/255,58/255),
              rgb(0/255,114/255,189/255), rgb(74/255,76/255,191/255),
              rgb(103/255,97/255,156/255), rgb(42/255,122/255,155/255))
  }else{Col2=ModuleColor1}
  scRNA2 <- scRNA12[, 1:ncol(scRNA12)]
  scRNA21<-apply(scRNA2, 2, as.numeric)
  rownames(scRNA21)<-rownames(scRNA2)
  scRNA3 <- Kmeans_heatmap(scRNA21, K1=1, RowGroup1=RowGroup1, Scale1=Scale1,
                           Gene1=Gene1, clustering_distance_rows='correlation',
                           NumRowBlank1=NumRowBlank1, show_colnames=show_colnames,
                           legend1=legend1, cluster_cols=F, Show.Module=T,
                           Color1=Color1, ModuleColor1=Col2, ModuleScale1=ModuleScale1,
                           RevOrder1=RevOrder1)
}



Kmeans_heatmap <- function(RNA1, K1=1, Gene1=NULL, RowGroup1=NULL, ColumnGroup1=NULL, Scale1='none', Range1=c(-Inf,Inf), Reorder1=T, RevOrder1=-1, clustering_distance_rows='euclidean', clustering_method='complete', Show.Module=F, Color1=NULL, show_colnames=T, NumRowBlank1=10, NumColumnBlank1=10, NAcolum1=NULL, ModuleColor1=NULL, ModuleScale1=10, cluster_cols=F, fontsize=10, legend1=T, border_color='white', ByPanel=F){

  if(Scale1=='row'){ RNA1 <- t(scale(t(RNA1))) }

  if(!is.null(ColumnGroup1)){
    print('sepate columns according to varible ColumnGroup1')
    ColumnBlank1 <- array(0, dim=c(nrow(RNA1), NumColumnBlank1))
    uColumnGroup1 <- unique(ColumnGroup1)
    if(length(uColumnGroup1)==1){
    }else{
      for(i in 1:length(uColumnGroup1)){
        RNA12 <- RNA1[, ColumnGroup1==uColumnGroup1[i]]
        if(i==1){ RNA21 <- cbind(RNA12, ColumnBlank1)
        }else if(i<length(uColumnGroup1)){
          RNA21 <- cbind(RNA21, RNA12, ColumnBlank1)
        }else{ RNA21 <- cbind(RNA21, RNA12) }
      }
    }
  }else{ RNA21 <- RNA1 }

  if(is.null(RowGroup1)){
    if(!is.null(NAcolum1)){
      cRNA1 <- kmeans(RNA1[, -NAcolum1], K1)
      RNA02 <- cbind(cRNA1$cluster, RNA1[, -NAcolum1])
      Cluster1 <- cRNA1$cluster
    }else{
      if(K1==1){ Cluster1 <- rep(1, nrow(RNA1))
      }else{ cRNA1 <- kmeans(RNA1, K1); Cluster1 <- cRNA1$cluster }
      RNA02 <- cbind(Cluster1, RNA1)
    }
    RNA2 <- cbind(Cluster1, RNA21); NameInd1 <- 1:K1
    colnames(RNA2)[1] <- c('KmeansGroup'); print(table(RNA2[, 'KmeansGroup']))
  }else{
    if(is.factor(RowGroup1)){
      Name1 <- levels(RowGroup1); Name2 <- sort(levels(RowGroup1));
      NameInd1 <- match(Name1, Name2)
      RowGroup1 <- as.numeric(RowGroup1); uRowGroup1 <- NameInd1;
    }else{ uRowGroup1 <- sort(unique(RowGroup1)) }

    if(!is.null(NAcolum1)){ RNA02 <- cbind(RowGroup1, RNA1[, -NAcolum1])
    }else{ RNA02 <- cbind(RowGroup1, RNA1) }
    RNA2 <- cbind(RowGroup1, RNA21);
    K1 <- length(uRowGroup1)
    colnames(RNA2)[1] <- c('KmeansGroup')
    tRNA2 <- table(RNA2[, 'KmeansGroup']);
    if(is.factor(RowGroup1)){ names(tRNA2) <- Name2;
    tRNA2 <- tRNA2[NameInd1];
    }
    print(tRNA2)
  }

  RNA22 <- c()
  RowBlank1 <- array(0, dim=c(NumRowBlank1, ncol(RNA2)))
  colnames(RowBlank1) <- colnames(RNA2)
  for(i in 1:K1){
    if(is.null(RowGroup1)){
      RNA20 <- RNA2[RNA2[, 'KmeansGroup']==i, ]
      RNA03 <- RNA02[RNA02[, 1]==i, ]
    }else{
      RNA20 <- RNA2[RNA2[, 'KmeansGroup']==uRowGroup1[i], ]
      RNA03 <- RNA02[RNA02[, 1]==uRowGroup1[i], ]
    }
    if(Reorder1==T){
      if(nrow(RNA03)>1){
        Hier1 <- hclust(as.dist((1 - cor(t(RNA03[, 2:ncol(RNA03)])))/2))
        if(RevOrder1[1]!=-1){ RevOrder2 <- F;
        for(j in 1:length(RevOrder1)){
          if(RevOrder1[j]==i){ RevOrder2 <- T; break }
        }
        if(RevOrder2==T){ Ind1 <- rev(Hier1$order)
        }else{ Ind1 <- Hier1$order }
        }else{ Ind1 <- Hier1$order }
      }else{ Ind1 <- 1:nrow(RNA20) }
    }else{ Ind1 <- 1:nrow(RNA20) }

    if(i!=K1){ RNA22 <- rbind(RNA22, RNA20[Ind1, ], RowBlank1)
    }else{ RNA22 <- rbind(RNA22, RNA20[Ind1, ]) }
  }

  print('Revise outlier')
  RNA23 <- RNA22[, 2:ncol(RNA22)]
  RNA23[RNA23<Range1[1]] <- Range1[1]
  RNA23[RNA23>Range1[2]] <- Range1[2]
  RNA3 <- cbind(RNA22[,1], RNA23)
  colnames(RNA3)[1] <- 'Module'
  RNA4 <- RNA22[RNA22[,1]!=0, ]

  if(is.null(Gene1)){ show_rownames <- F; Gene2 <- ''
  }else if(Gene1[1]=='all'){ show_rownames <- T; Gene2 <- rownames(RNA3)
  }else{ show_rownames <- T; Gene2 <- rownames(RNA3)
  Gene2[!is.element(Gene2, Gene1)] <- '';
  Gene3 <- rownames(RNA3)[is.element(rownames(RNA3), Gene1)]; print(sort(Gene3))
  }

  if(is.null(Color1)){ Color1 <- c(rgb(72/255,85/255,167/255), rgb(255/255,255/255,255/255), rgb(239/255,58/255,37/255)) }

  if(Show.Module==T){

    if(is.null(ModuleColor1)){
      ModuleColor1 <- c(rgb(255/255,255/255,255/255), rgb(152/255,152/255,152/255), rgb(72/255,85/255,167/255))
    }else{
      if(!is.null(RowGroup1) & is.factor(RowGroup1)){ ModuleColor1 <- ModuleColor1[c(1,NameInd1+1)]; }
    }

    if(K1==1){
      ph1 <- pheatmap::pheatmap(RNA3[, 1], clustering_distance_rows=clustering_distance_rows, show_rownames=F, show_colnames=show_colnames, border_color='white', cluster_rows=F, cluster_cols=cluster_cols, color = ModuleColor1, legend=F, silent=T, breaks=seq(1, nrow(RNA3)))
    }else{
      ph1 <- pheatmap::pheatmap(RNA3[, 1], clustering_distance_rows=clustering_distance_rows, show_rownames=F, show_colnames=show_colnames, border_color='white', cluster_rows=F, cluster_cols=cluster_cols, color = ModuleColor1, legend=F, silent=T)
    }
    if(ByPanel==T){
      uColumnGroup1 <- unique(ColumnGroup1)
      RNA31 <- RNA3[, 2:(length(ColumnGroup1[ColumnGroup1==uColumnGroup1[1]])+1)]
      ph12 <- pheatmap::pheatmap(RNA3[, 2:(length(ColumnGroup1[ColumnGroup1==uColumnGroup1[1]])+1)], clustering_distance_rows=clustering_distance_rows, clustering_method=clustering_method, show_rownames=show_rownames, show_colnames=show_colnames, labels_row=Gene2, border_color=border_color, cluster_rows=F, cluster_cols=cluster_cols, color = colorRampPalette(Color1)(100), fontsize=fontsize, legend=legend1, silent=T)
      ph2 <- pheatmap::pheatmap(RNA31, clustering_distance_rows=clustering_distance_rows, clustering_method=clustering_method, show_rownames=show_rownames, show_colnames=show_colnames, labels_row=Gene2, border_color=border_color, cluster_rows=F, cluster_cols=cluster_cols, color = colorRampPalette(Color1)(100), fontsize=fontsize, legend=legend1, silent=T)
      plot_list <- list(); plot_list[[1]] <- ph1[[4]]; plot_list[[2]] <- ph2[[4]]
      ModuleScale2 <- rep(2, ceiling(ncol(RNA31)/ncol(RNA3)*ModuleScale1))
      if(length(uColumnGroup1)>1){
        for(i in 2:length(uColumnGroup1)){
          GroupLeng1 <- length(ColumnGroup1[ColumnGroup1<uColumnGroup1[i]])
          GroupLeng2 <- length(ColumnGroup1[ColumnGroup1==uColumnGroup1[i]])
          RNA32 <- RNA3[, (GroupLeng1+NumColumnBlank1*(i-1)+2):(GroupLeng1+NumColumnBlank1*(i-1)+GroupLeng2+1)]
          ph3 <- pheatmap::pheatmap(RNA32, clustering_distance_rows=clustering_distance_rows, clustering_method=clustering_method, show_rownames=show_rownames, show_colnames=show_colnames, labels_row=Gene2, border_color=border_color, cluster_rows=F, cluster_cols=cluster_cols, color = colorRampPalette(Color1)(100), fontsize=fontsize, legend=legend1, silent=T)
          plot_list[[i+1]] <- ph3[[4]]
          ModuleScale2 <- c(ModuleScale2, rep(i+1, ceiling(ncol(RNA32)/ncol(RNA3)*ModuleScale1)))
        } }
      layout_ncol <- length(uColumnGroup1)+1; layout_matrix <- matrix(c(1, ModuleScale2), nrow=1)
    }else{ ph2 <- pheatmap::pheatmap(RNA3[, 2:ncol(RNA3)], clustering_distance_rows=clustering_distance_rows, clustering_method=clustering_method, show_rownames=show_rownames, show_colnames=show_colnames, labels_row=Gene2, border_color=border_color, cluster_rows=F, cluster_cols=cluster_cols, color = colorRampPalette(Color1)(100), fontsize=fontsize, legend=legend1, silent=T)
    plot_list <- list(ph1[[4]], ph2[[4]]); layout_ncol <- 2
    layout_matrix <- matrix(c(1, rep(2,ModuleScale1)), nrow=1)
    }

    g <- gridExtra::grid.arrange(arrangeGrob(grobs= plot_list, ncol=layout_ncol, layout_matrix=layout_matrix))
  }else{
    pheatmap::pheatmap(RNA3[, 2:ncol(RNA3)], clustering_distance_rows=clustering_distance_rows, clustering_method=clustering_method, show_rownames=show_rownames, show_colnames=show_colnames, labels_row=Gene2, border_color=border_color, cluster_rows=F, cluster_cols=cluster_cols, color = colorRampPalette(Color1)(100), fontsize=fontsize, legend=legend1)
  }

  return(RNA4)
}


